services:
  - type: web
    name: smartqueue
    runtime: node
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node server/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
